name: Checkov Testing
on:
  pull_request:
    branches: [dev-master,feature/qa]
  push:
    branches:
      - feat/sta
jobs:
  checkov_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     #- name: Setup Terraform
        #uses: hashicorp/setup-terraform@v4
        #with:
          #terraform_version: latest
      
      #- name: Set up Python
      #  uses: actions/setup-python@v4
      #  with:
      #    python-version: 3.12.4
      
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          output_format: sarif
          output_file_path: results.sarif

      - name: Console
        run: ls -l

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        
        # Results are generated only on a success or failure
        # this is required since GitHub by default won't run the next step
        # when the previous one has failed. Security checks that do not pass will 'fail'.
        # An alternative is to add `continue-on-error: true` to the previous step
        # Or 'soft_fail: true' to checkov.
        if: success() || failure()
        with:
          sarif_file: results.sarif

      

      #- name: Install Checkov
      #  run: |
      #   python -m pip install --upgrade pip
      #   pip install checkov  #
      
      #- name: Install Checkov
      #  run: pip install checkov

      #- name: Run Checkov scan
      #  run: |
      #    mkdir -p reports
      #    checkov -d . --quiet --output json > reports/checkov_report.json
      

      #- name: Console
      #  run: ls -l

      
      #- name: Save Checkov Report
      #  run: |
      #    mkdir -p reports
      #    cp results.sarif reports/checkov_report.sarif

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: 'squ_21a5cd2d91f35cee6cbd58a6c7c525a4526aa542'
          SONAR_HOST_URL: sonar.yomafleet.tech
        #with:
        #  projectBaseDir: .
        #  extraArgs: |
        #    -Dsonar.externalIssuesReportPaths=reports.sarif
        #    -Dsonar.inclusions=**/*.tf
        #    -Dsonar.exclusions=**/checkov_reports/**